### ISSUE TITLE
docs: add a link to readme.md

### ISSUE THREAD

**Issue by aliceandbob-io** [aliceandbob-io/aliceandbob-desktop#1]
A new link is to be added to ```README.md``` which refers to the electronjs.org page.
Link to be added: https://www.electronjs.org/apps/aliceandbob-io

The link should appear in third position below the two existing links and following the same format (see below):

## Download it ⬇️

- From the repo's Github page: [releases](https://github.com/aliceandbob-io/aliceandbob-desktop/releases)
- From [aliceandbobio](https://aliceandbob.io/)

**Comment by shivani1120** [comment]
Hey  @aliceandbob.io. I would like to work on this issue.

**Comment by aliceandbob-io** [comment]
Thanks @shivani1120! I've just assigned you the issue 🚀

**Comment by rosetanya898** [comment]
I have opened pull request #2

**Comment by aliceandbob-io** [comment]
Thanks @rosetanya898, however this issue is already assigned to @shivani1120.

**Comment by aliceandbob-io** [comment]
@shivani1120, can you confirm that you are still working on this issue? Otherwise I'll let @rosetanya898 dealing with it.

**Comment by shivani1120** [comment]
I will work on this
