### ISSUE TITLE
Action buttons don't work

### ISSUE THREAD

**Issue by piotreknow02** [aliceandbob-io/aliceandbob-desktop#9]
# "Generate", "Encrypt", "Decrypt" and view password buttons don't work.
It looks like there is not action attached to it.
I've checked the browser console and it says that "$ is not defined"
That is probably blocking DOM event handlers which is causing the error

### OS and device info
Hardware: MacBook Pro 2017
OS: MacOS Monterey 12.2.1

Screenshot from browser console below:
<img width="544" alt="Zrzut ekranu 2022-03-5 o 22 41 51" src="https://user-images.githubusercontent.com/65082017/156900838-e874ba7b-2698-40a7-9df6-f26d0e5236cd.png">

**Comment by aliceandbob-io** [comment]
Thanks for reporting this issue @piotreknow02!. I have no much time these days, but I'll try to dig into it asap 👍
